### ISSUE TITLE
Add WebHooks for Waffle.io

### ISSUE THREAD

**Issue by carlin010** [niklasfink/class-survey#4]
Waffle needs an admin of niklasfink/class-survey to configure webhooks, to enable real time updates from GitHub.

Go to the Master branch. Click on the Ready button at the top of the README.md file and sign in to GitHub to configure web hooks.

**Comment by carlin010** [comment]
Let me know what you think. I know we need some sort of kanban board for our development life cycle.

**Comment by niklasfink** [comment]
Waffle looks good, let's use this.

**Comment by niklasfink** [comment]
@carlin010 size of an issue would be the time in hours?
